### ISSUE TITLE
add SSL support

### ISSUE THREAD

**Issue by dbist** [cockroachdb/django-cockroachdb#107]
on a secure cluster, getting error if settings.py is missing `'sslmode':'require'` option. The error message is 
```
Attaching to lb, cockroach-django_web_1, roach-2, roach-1, roach-0, roach-cert
web_1         | Watching for file changes with StatReloader
web_1         | Performing system checks...
web_1         |
web_1         | System check identified no issues (0 silenced).
web_1         | Exception in thread django-main-thread:
web_1         | Traceback (most recent call last):
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web_1         |     self.connect()
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 24, in inner
web_1         |     return func(*args, **kwargs)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 197, in connect
web_1         |     self.connection = self.get_new_connection(conn_params)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 24, in inner
web_1         |     return func(*args, **kwargs)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
web_1         |     connection = Database.connect(**conn_params)
web_1         |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
web_1         |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_1         | psycopg2.OperationalError: ERROR:  password authentication failed for user myprojectuser
web_1         | ERROR:  node is running secure mode, SSL connection required
web_1         |
web_1         |
web_1         | The above exception was the direct cause of the following exception:
web_1         |
web_1         | Traceback (most recent call last):
web_1         |   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
web_1         |     self.run()
web_1         |   File "/usr/local/lib/python3.7/threading.py", line 870, in run
web_1         |     self._target(*self._args, **self._kwargs)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
web_1         |     fn(*args, **kwargs)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
web_1         |     self.check_migrations()
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 458, in check_migrations
web_1         |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
web_1         |     self.loader = MigrationLoader(self.connection)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
web_1         |     self.build_graph()
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
web_1         |     self.applied_migrations = recorder.applied_migrations()
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 76, in applied_migrations
web_1         |     if self.has_table():
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
web_1         |     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 24, in inner
web_1         |     return func(*args, **kwargs)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 260, in cursor
web_1         |     return self._cursor()
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 236, in _cursor
web_1         |     self.ensure_connection()
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 24, in inner
web_1         |     return func(*args, **kwargs)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web_1         |     self.connect()
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
web_1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web_1         |     self.connect()
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 24, in inner
web_1         |     return func(*args, **kwargs)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 197, in connect
web_1         |     self.connection = self.get_new_connection(conn_params)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 24, in inner
web_1         |     return func(*args, **kwargs)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
web_1         |     connection = Database.connect(**conn_params)
web_1         |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
web_1         |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_1         | django.db.utils.OperationalError: ERROR:  password authentication failed for user myprojectuser
web_1         | ERROR:  node is running secure mode, SSL connection required
```
the message is muted if the following is introduced into settings.py

```bash
 'OPTIONS': {
            'sslmode': 'require',
        },
```

**Comment by timgraham** [comment]
Django is using psycopg2 to connect. Adding `'sslmode': 'require'` looks correct as Django passes that to psycopg2. What happens after you add that?

**Comment by dbist** [comment]
once I bypass the ssl issue, I get the following error ```
web_1         | Watching for file changes with StatReloader
web_1         | Performing system checks...
web_1         |
web_1         | System check identified no issues (0 silenced).
web_1         | Exception in thread django-main-thread:
web_1         | Traceback (most recent call last):
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web_1         |     self.connect()
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 24, in inner
web_1         |     return func(*args, **kwargs)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 197, in connect
web_1         |     self.connection = self.get_new_connection(conn_params)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 24, in inner
web_1         |     return func(*args, **kwargs)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
web_1         |     connection = Database.connect(**conn_params)
web_1         |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
web_1         |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_1         | psycopg2.OperationalError: ERROR:  password authentication failed for user myprojectuser
web_1         |
web_1         |
web_1         | The above exception was the direct cause of the following exception:
web_1         |
web_1         | Traceback (most recent call last):
web_1         |   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
web_1         |     self.run()
web_1         |   File "/usr/local/lib/python3.7/threading.py", line 870, in run
web_1         |     self._target(*self._args, **self._kwargs)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
web_1         |     fn(*args, **kwargs)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
web_1         |     self.check_migrations()
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 458, in check_migrations
web_1         |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
web_1         |     self.loader = MigrationLoader(self.connection)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
web_1         |     self.build_graph()
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
web_1         |     self.applied_migrations = recorder.applied_migrations()
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 76, in applied_migrations
web_1         |     if self.has_table():
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
web_1         |     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 24, in inner
web_1         |     return func(*args, **kwargs)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 260, in cursor
web_1         |     return self._cursor()
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 236, in _cursor
web_1         |     self.ensure_connection()
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 24, in inner
web_1         |     return func(*args, **kwargs)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web_1         |     self.connect()
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
web_1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web_1         |     self.connect()
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 24, in inner
web_1         |     return func(*args, **kwargs)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 197, in connect
web_1         |     self.connection = self.get_new_connection(conn_params)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 24, in inner
web_1         |     return func(*args, **kwargs)
web_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
web_1         |     connection = Database.connect(**conn_params)
web_1         |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
web_1         |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_1         | django.db.utils.OperationalError: ERROR:  password authentication failed for user myprojectuser
```

**Comment by timgraham** [comment]
You need to put whatever options that psycopg2 needs in Django's OPTIONS. Based on [this example](https://www.cockroachlabs.com/docs/stable/build-a-python-app-with-cockroachdb.html), `sslrootcert`, `sslkey`, and `sslcert` look like good bets.

**Comment by dbist** [comment]
proper way to configure is with 
```
DATABASES = {
    'default': {
        'ENGINE': 'django_cockroachdb',
        'NAME': 'myproject',
        'USER': 'myprojectuser',
        'HOST': 'roach-0',
        'PORT': '26257',
        'OPTIONS': {
            'sslmode': 'verify-full',
            'sslrootcert': '/certs/ca.crt',
            'sslcert': '/certs/client.myprojectuser.crt',
            'sslkey': '/certs/client.myprojectuser.key',
        },
    },
}
```
