### ISSUE TITLE
in_retry decorator not threadsafe

### ISSUE THREAD

**Issue by adamchainz** [cockroachdb/django-cockroachdb#121]
The in_retry example [on the tutorial](
https://www.cockroachlabs.com/docs/stable/build-a-python-app-with-cockroachdb-django.html) uses a global variable `in_retry`. This won't work when deployed under a threaded WSGI server, since the variable will be shared between threads.  [contextvars](https://docs.python.org/3/library/contextvars.html) are the newest Python solution to this problem, but probably a bigger rewrite to a loop or recursion would be better.

**Comment by awoods187** [comment]
@apantel can you take a look at this?

**Comment by apantel** [comment]
Yes, I have a fix for this.

**Comment by apantel** [comment]
I can either do this as a global map from Thread -> bool, or just leave it off and recommend against nesting in a comment.

**Comment by timgraham** [comment]
Fixed in https://github.com/cockroachdb/docs/pull/6412.

**Comment by adamchainz** [comment]
Thanks!
