### ISSUE TITLE
Wrong URL path syntax in django tutorial

### ISSUE THREAD

**Issue by adamchainz** [cockroachdb/django-cockroachdb#122]
The URL syntax in [the tutorial](https://www.cockroachlabs.com/docs/stable/build-a-python-app-with-cockroachdb-django.html) uses `from django.conf.urls import url` which is the old import for regex based paths on old versions of Django, but it uses the new syntax. [The `django.urls.path` function](https://docs.djangoproject.com/en/3.0/ref/urls/#django.urls.path) was probably intended.

**Comment by awoods187** [comment]
@ericharmeling and @apantel could you take a look at this?

**Comment by timgraham** [comment]
The docs are in a different repo. The PR that I opened yesterday is https://github.com/cockroachdb/docs/pull/6404.
