### ISSUE TITLE
TeamCity build directory is sometimes reused

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/django-cockroachdb#141]
I've seen an intermittent issue (first reported in Slack months ago) where TeamCity seems to reuse an old environment such that there are files from a past run:
```
Starting: /home/agent/temp/agentTmp/custom_script3613706416485726622 in directory: /home/agent/work/323e0f636337ffe3

 + ./teamcity-build/build-teamcity.sh v19.2.6
...

git clone --depth 1 --single-branch --branch cockroach-master https://github.com/timgraham/django _django_repo
fatal: destination path '_django_repo' already exists and is not an empty directory.
```
I don't know enough about TeamCity to say what the proper resolution is.

**Comment by rafiss** [comment]
I last investigated this 2 months ago and didn't have any luck. The farthest I got was that it might relate to the "Use mirrors" setting on the VCS configuration:
> When this option is enabled, TeamCity creates a separate clone of the repository on each agent and uses it in the checkout directory via git alternates.

**Comment by rafiss** [comment]
I found this option elsewhere in the TeamCity settings, and it seems promising. It was previously unchecked, so I just enabled it.
<img width="771" alt="image" src="https://user-images.githubusercontent.com/1320573/83082287-0252d700-a051-11ea-86eb-5866b2ac5bfe.png">

**Comment by timgraham** [comment]
Great! I'll reopen if I see this again.
