### ISSUE TITLE
Does django-cockroachdb support JSONField 

### ISSUE THREAD

**Issue by daadu** [cockroachdb/django-cockroachdb#152]
I am using postgres currently which has JSONField (postgres specific field as mention in django docs.)

Django 3.1 is introducing native [JSONField](https://docs.djangoproject.com/en/3.1/ref/models/fields/#jsonfield) support. Since cockroachdb already supports `jsonb` object.

I am thinking of migrating my project to cockroach db. Does this package currently (or planned to) support `JSONField`

**Comment by daadu** [comment]
This https://github.com/django/django/commit/f59a2b730685fc62c5cb44101f54faf8921d9bc7 commit suggests somthing about it, I am not sure what.

**Comment by daadu** [comment]
There is this https://github.com/django/django/pull/12920 PR as well.

**Comment by daadu** [comment]
> * Third-party database backends must implement support for ``JSONField`` or set
>   ``DatabaseFeatures.supports_json_field`` to ``False``. If storing primitives
>   is not supported, set ``DatabaseFeatures.supports_primitives_in_json_field``
>   to ``False``. If there is a true datatype for JSON, set
>   ``DatabaseFeatures.has_native_json_field`` to ``True``.
> 
> * Third party database backends must implement introspection for ``JSONField``
>   or set ``can_introspect_json_field`` to ``False``.

From Django 3.1 docs.

**Comment by daadu** [comment]
Digging some code into this package I found that this backend inherits the default `DatabaseFeatures`, without setting `DatabaseFeatures.supports_json_field` and `DatabaseFeatures.supports_primitives_in_json_field` to `False` or  `DatabaseFeatures.has_native_json_field` to `True`.


My guess is if cockroachdb has "true" JSON datatype this package should explicitly set `DatabaseFeatures.has_native_json_field` to `True`

**Comment by daadu** [comment]
```python
    # Does the backend support JSONField?
    supports_json_field = True
    # Can the backend introspect a JSONField?
    can_introspect_json_field = True
    # Does the backend support primitives in JSONField?
    supports_primitives_in_json_field = True
    # Is there a true datatype for JSON?
    has_native_json_field = False
    # Does the backend use PostgreSQL-style JSON operators like '->'?
    has_json_operators = False
```

This are the default values of features related to JSON. Check https://github.com/django/django/blob/master/django/db/backends/base/features.py#L291

**Comment by daadu** [comment]
`postgres` backend overrides the following

```python
    has_native_json_field = True
    has_json_operators = True
```

**Comment by daadu** [comment]
This looks like this backend (without any changes) should support `JSONField` when it is released with Django 3.1. 

Am I right?

**Comment by daadu** [comment]
Does it also work with `django.contrib.postgres.fields.JSONField` ? If it does then I do not need to wait for Django 3.1 release

**Comment by timgraham** [comment]
There's a commit in https://github.com/cockroachdb/django-cockroachdb/pull/95 that adds support for JSONField in Django 3.1. For older versions of Django, the version in contrib.postgres isn't officially supported but it may work to some extent.
