### ISSUE TITLE
enable QuerySet.select_for_update() and select_for_update(of=...)

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/django-cockroachdb#153]
CockroachDB added support in 20.1 but the feature isn't enabled in Django.

**Comment by timgraham** [comment]
One of Django's tests is hanging in line 486 (the line below the comment "Since this isn't using FOR UPDATE, it won't block").

https://github.com/django/django/blob/83fbaa92311dd96e330496a0e443ea71b9c183e2/tests/select_for_update/tests.py#L459-L503

@nvanbenschoten as the author of https://github.com/cockroachdb/cockroach/pull/45701, are you a good person to check if this might be a bug in CockroachDB? Let me know if you need me to turn the test into a series of steps to reproduce. Thanks!

**Comment by nvanbenschoten** [comment]
@timgraham thanks for filing. I think we're seeing something similar to what is discussed in https://forum.cockroachlabs.com/t/select-for-update-more-restrictive-than-postgresql/3860. The TL;DR is that CockroachDB is deliberately (at least for now) more pessimistic in terms of blocking than Postgres is in these kinds of situations.
