### ISSUE TITLE
Migration from IntegerField to AutoField doesn't set default to unique_rowid()

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/django-cockroachdb#157]
### Environment
I have tested this with django==2.2.6/django-cockroachdb==2.2.1 as well as django==3.0.8/django-cockroachdb==3.0.1.

### To reproduce:
- Make a new app.
- Create `models.py`:

```
from django.db import models

class Widgets(models.Model):
    widget_id = models.IntegerField(primary_key=True, serialize=False)
    widget_name = models.CharField(max_length=400)
```

- Run `python manage.py makemigrations` then `python manage.py migrate`
- Edit `models.py`:
```
from django.db import models

class Widgets(models.Model):
    widget_id = models.AutoField(primary_key=True, serialize=False)
    widget_name = models.CharField(max_length=400)
```
- Run `python manage.py makemigrations` then `python manage.py migrate`

(The migrations files should look like this:)
```
# Generated by Django 3.0.8 on 2020-08-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Widgets',
            fields=[
                ('widget_id', models.IntegerField(primary_key=True, serialize=False)),
                ('widget_name', models.CharField(max_length=400)),
            ],
        ),
    ]
```

```
# Generated by Django 3.0.8 on 2020-08-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_migrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgets',
            name='widget_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
```

### Expected behavior
The `test_migrations_widgets` table should have a primary key named `widget_id` with `DEFAULT unique_rowid()`.

### Actual Behavior
But instead, it has the following schema
```
  column_name |  data_type   | is_nullable | column_default | generation_expression |  indices  | is_hidden
--------------+--------------+-------------+----------------+-----------------------+-----------+------------
  widget_id   | INT8         |    false    | NULL           |                       | {primary} |   false
  widget_name | VARCHAR(400) |    false    | NULL           |                       | {}        |   false
```

**Comment by rafiss** [comment]
Actually, maybe there is a more general problem with adding default values. For example, after doing the above, I added the following field to my `Widgets` model:
```
    widget_ok = models.BooleanField(default=False)
```

Then I generated/ran migrations. The column was added, but without a default value.

**Comment by rafiss** [comment]
@timgraham do you know why this might be happening, or which part of the code I should direct my attention to?

**Comment by timgraham** [comment]
I have a patch I expect to publish later today.

On the second issue, that default only affects Python. Django doesn't use database defaults, except temporarily when adding a column to an existing table.

**Comment by vy-ton** [comment]
> On the second issue, that default only affects Python. Django doesn't use database defaults
Hi @timgraham, can you help me understand what "only affects Python" means?

If Django doesn't create `DEFAULT` value constraints, then I would expect the `AutoField` migration to not perform as expected?

**Comment by rafiss** [comment]
I was taking a look at these docs: https://docs.djangoproject.com/en/3.0/ref/models/fields/#default

To clarify, I wasn't expecting a default value to be populated for existing rows. But I saw that `column_default` was not set when displaying the schema, which I would have expected.

```
> show columns from widgets;

  column_name |  data_type   | is_nullable | column_default | generation_expression |  indices  | is_hidden
--------------+--------------+-------------+----------------+-----------------------+-----------+------------
  widget_id   | INT8         |    false    | NULL           |                       | {primary} |   false
  widget_name | VARCHAR(400) |    true     | NULL           |                       | {}        |   false
  widget_ok   | BOOL         |    true     | NULL           |                       | {}        |   false
```

**Comment by timgraham** [comment]
Quoting [Django's documentation](https://docs.djangoproject.com/en/stable/ref/models/fields/#default) for `Field.default`: "The default value is used when new model instances are created and a value isn’t provided for the field." `Field.default` isn't put in `column_default` but there's [an open ticket](https://code.djangoproject.com/ticket/470) for that feature.

`AutoField` doesn't use `Field.default`. Instead, the `DEFAULT unique_rowid()` expression is here:
https://github.com/cockroachdb/django-cockroachdb/blob/9d0ffc758b9a09c7618f48592640c126a783406f/django_cockroachdb/base.py#L41-L45

Django's PostgreSQL backend doesn't consider `data_types_suffix` when altering fields because `AutoField` uses PostgreSQL's  serial type instead.

PR: https://github.com/cockroachdb/django-cockroachdb/pull/159

I'll amend Django's test for this issue to ensure it doesn't regress. While working on that, I noticed [a similar issue affects PostgreSQL](https://code.djangoproject.com/ticket/24533) (one of my test amendments doesn't work there).
