### ISSUE TITLE
Add support for client side certificates

### ISSUE THREAD

**Issue by robert-kisteleki** [cockroachdb/django-cockroachdb#173]
A CockroachDB client can use a key+certificate for authentication instead of user+password. See docs at https://www.cockroachlabs.com/docs/stable/authentication.html

This affects the dbshell implementation: password doesn't exist, username becomes optional.

It also affects the django DB connections themselves. I believe it means the connection needs to support the (postgres) client authentication protocol (https://www.postgresql.org/docs/11/auth-cert.html ?)

**Comment by timgraham** [comment]
`dbshell` simply invokes `cockroach sql ...`. Are you able to connect that way with some command line flags?

Django's connections use psycopg2. The available `'OPTIONS'` for the `DATABASES` settings are listed here: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS

If it's possible to use client-side certificates with psycopg2, I'm doubtful any changes are needed in Django or in django-cockroachdb but let me know if you can connect with psycopg2 but not with Django.

**Comment by robert-kisteleki** [comment]
> `dbshell` simply invokes `cockroach sql ...`. Are you able to connect that way with some command line flags?

Yes. `cockroach sql --certs-dir=DIR --user=USER` itself works.

> Django's connections use psycopg2. The available `'OPTIONS'` for the `DATABASES` settings are listed here: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS
> 
> If it's possible to use client-side certificates with psycopg2, I'm doubtful any changes are needed in Django or in django-cockroachdb but let me know if you can connect with psycopg2 but not with Django.

In the end things worked based on what's written in the README. I think I have two notes:
* when using username+password: the password must obviously be set in the settings for the app to work, but it prevents dbshell from starting
* when using key+cert: the USER setting must match what's in the certificate, which is likely not `root`

I guess the first one could be helped by not passing `--password` to `cockroach sql` in the dbshell case.

**Comment by timgraham** [comment]
Thanks. `--password` shouldn't be passed in `dbshell` (https://github.com/cockroachdb/django-cockroachdb/pull/175), and I agree about using a better username in the readme (https://github.com/cockroachdb/django-cockroachdb/pull/177).
