### ISSUE TITLE
dbshell crash: unknown flag: --password

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/django-cockroachdb#174]
As reported at https://github.com/cockroachdb/django-cockroachdb/issues/171#issuecomment-710266876, 
```
$ manage.py dbshell
Usage:
  cockroach sql [options] [flags]
[...]

ERROR: unknown flag: --password
Failed running "sql"
CommandError: "cockroach sql --database=[DATABASE] --certs-dir=[CERTSDIR] --user=[USER] --password=[PASSWORD] --host=[HOST] --port=[PORT]" returned non-zero exit status 1.
```
It looks like `cockroach sql` has no way to provide a password besides the `--url postgresql://[user[:passwd]@]host[:port]/[db][?parameters...]` option, however, that could be a security issue since the password would be viewable by other system users if they invoke `ps aux | grep cockroach`.

**Comment by rafiss** [comment]
could the `COCKROACH_URL` env var be used for this? if it's set, then the `cockroach` command will use that URL to connect.

**Comment by timgraham** [comment]
That seems promising. I created https://github.com/cockroachdb/django-cockroachdb/issues/180.
