### ISSUE TITLE
clone test databases without cockroach dump

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/django-cockroachdb#189]
From the [20.2 release notes](https://www.cockroachlabs.com/docs/releases/v20.2.0): 

> The `cockroach dump` command is now deprecated. Instead, back up your data in a full backup, export your data in plain text format, or view table schema in plaintext with SHOW CREATE TABLE.

django-cockroachdb uses `cockroach dump` to clone the test database, so that solution will have to be revised.
https://github.com/cockroachdb/django-cockroachdb/blob/6304e41fc5725fcfe53b851498529c339ba89f20/django_cockroachdb/creation.py#L245-L250

**Comment by rafiss** [comment]
I wonder if [backup/restore](https://www.cockroachlabs.com/docs/stable/backup.html) could be used here, or if there's too much overhead involved with getting that working.

**Comment by rafiss** [comment]
We've filed this related issue in the database https://github.com/cockroachdb/cockroach/issues/53488 (different initial motivation, but seems relevant here)

**Comment by timgraham** [comment]
I'm not sure `SHOW CREATE` would be sufficient as the data in the tables also needs to be copied.

I got something working with backup/restore. I tested a statement like `"BACKUP DATABASE %s TO 'nodelocal://self/test'"`. One thing I ran into is that CockroachDB has to be started with the `--external-io-dir` option, otherwise you get a somewhat puzzling error like this:
```
$ ./tests/runtests.py --settings=test_roach expressions basic admin_views sites_tests 
Testing against Django installed in '/home/tim/code/django/django' with up to 3 processes
Creating test database for alias 'default'...
Cloning test database for alias 'default'...
Traceback (most recent call last):
  File "/home/tim/code/django/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.InternalError: local file access is disabled


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/code/django/./tests/runtests.py", line 568, in <module>
    failures = django_tests(
  File "/home/tim/code/django/./tests/runtests.py", line 310, in django_tests
    failures = test_runner.run_tests(
  File "/home/tim/code/django/django/test/runner.py", line 695, in run_tests
    old_config = self.setup_databases(aliases=databases)
  File "/home/tim/code/django/django/test/runner.py", line 614, in setup_databases
    return _setup_databases(
  File "/home/tim/code/django/django/test/utils.py", line 178, in setup_databases
    connection.creation.clone_test_db(
  File "/home/tim/code/django/django/db/backends/base/creation.py", line 234, in clone_test_db
    self._clone_test_db(suffix, verbosity, keepdb)
  File "/home/tim/code/cockroach-django/django_cockroachdb/creation.py", line 243, in _clone_test_db
    self._clone_db(source_database_name, target_database_name)
  File "/home/tim/code/cockroach-django/django_cockroachdb/creation.py", line 256, in _clone_db
    cursor.execute("BACKUP DATABASE %s TO 'nodelocal://self/test%s'" % (source_database_name, id))
  File "/home/tim/code/django/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/tim/code/django/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/tim/code/django/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/tim/code/django/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.InternalError: local file access is disabled
```
Another thing is that I'm not sure if there's a way to "clean up" and delete the backup afterwards?

**Comment by rafiss** [comment]
Hmm interesting, I'd expect `--external-io-dir` to default to store things in `store/extern/`. But changing the startup flag sounds fine if that gets it working.

To clean up, we should just be able to `rm` the backup data.

**Comment by timgraham** [comment]
My thought was that it's not a great experience to require Django users to have to specify that flag to run their tests.

Yes, we can try to manually clean things up if necessary. It just seems unfortunate that this new path seems more complicated than using the deprecated dump/load functionality in CockroachDB.

**Comment by rafiss** [comment]
I'll ask someone from our Bulk IO team to weigh in here.

I don't understand about clean up though -- the old `cockroach dump` command (nor the `sql` loading command) also did not clean up the data dump

**Comment by timgraham** [comment]
Thanks. The current implementation with dump/load does everything in memory (see the code in this issue's description).

**Comment by rafiss** [comment]
Ah ok I see that it didn't used to persist to a file.

* The Bulk IO team advised me to suggest using a destination like `BACKUP DATABASE %s TO 'userfile://...`. It seems userfile doesn't need the external IO access.
* The way we recommend cleaning up the backup is with the command `cockroach userfile delete`. See more docs here: https://www.cockroachlabs.com/docs/v20.2/use-userfile-for-bulk-operations.html

**Comment by timgraham** [comment]
I did some performance testing.

Running Django's queries test app with two parallel workers and the current dump/load implementation of database cloning takes 4 minutes. Running the same app with cloning using backup to userfile takes 52 seconds. Running with a single worker (which doesn't require any database cloning) takes 37 seconds. So for this case, parallel testing offers no benefit.

Similarly, for Django's entire test suite (which has hundreds of tables):
- dump/load takes over 9 hours before I aborted it. At that point, it had only created two clones of the 'default' database (and still needed to do the same for the 'other' database, plus run the tests).
- Backup to userfile took 130 minutes.
- A single worker took 95 minutes.

Again, parallel workers offer no benefit.

Since database cloning seems to be so expensive, I think we should just disable parallel workers. It seems this will probably speed up tests for most cases.

**Comment by timgraham** [comment]
In case it's useful in the future, here's the implementation (with output for performance testing) of `DatabaseCreation.clone_test_db()` that uses backup to and restore from userfile:
```python
import time
backup_init = time.time()
with self._nodb_cursor() as cursor:
    cursor.execute(
        "BACKUP DATABASE %s TO 'userfile:///test%s'" % (
            source_database_name, target_database_name,
        )
    )
backup = int(time.time() - backup_init)
print('backup = %s' % backup)
restore_init = time.time()
with self._nodb_cursor() as cursor:
    cursor.execute(
        "RESTORE %s.* FROM 'userfile:///test%s' WITH into_db='%s'" % (
            source_database_name, target_database_name, target_database_name,
        )
    )
restore = int(time.time() - restore_init)
print('restore = %s' % restore)
print('total = %s' % (backup + restore))
```

**Comment by timgraham** [comment]
If it's of interest, each backup during a test run took longer than the previous one, although restore times were constant. 

|    Backup    |  Restore   |
| ------------ | ---------- |
|  3.5 minutes | 38 seconds |
|  6.1 minutes | 42 seconds |
| 10.2 minutes | 47 seconds |
| 12.9 minutes | 42 seconds |

I realized there might be an opportunity to make the cloning process a little smarter by trying to reuse the backup of each source database (thus for the case above, two backups and four restores would be required). Even so, it seems like CockroachDB slows when handling concurrent queries from parallel workers so I don't think things would be faster in the end.
