### ISSUE TITLE
Why not UUID PKs?

### ISSUE THREAD

**Issue by mlazowik** [cockroachdb/django-cockroachdb#212]
Is there any reason against using UUIDs as primary keys in Django? Cockroach docs say that if there's no need for roughly ordered numbers, UUIDs should be used, because using them spreads load evenly across nodes.

https://www.cockroachlabs.com/docs/stable/sql-faqs.html#how-do-i-generate-unique-slowly-increasing-sequential-numbers-in-cockroachdb

**Comment by timgraham** [comment]
I don't think so. You can certainly use UUID primary keys [as described in Django's documentation](https://docs.djangoproject.com/en/dev/ref/models/fields/#uuidfield).

If the `DEFAULT_AUTO_FIELD` setting [adds support for `UUIDField`](https://code.djangoproject.com/ticket/32577), we could recommend that.

**Comment by mlazowik** [comment]
Thanks!
