### ISSUE TITLE
Foreign Key indexing in CockroachDB >=20.2

### ISSUE THREAD

**Issue by Asgavar** [cockroachdb/django-cockroachdb#213]
Hi :wave: 

So [as we all know](https://www.cockroachlabs.com/docs/stable/foreign-key.html), in 20.2 our beloved insect stopped its indices auto-creation behavior for newly added FK constraints. Does this change extend to `django-cockroachdb`, so all columns that I _would_ want to have an index on should have it set up explicitly?

From what I see in the code here it looks like it indeed does, and the `db_index` parameter of the `ForeignKey` field ([defaulting to True](https://github.com/django/django/blob/76c0b32f826469320c59709d31e2f2126dd7c505/django/db/models/fields/related.py#L823)) doesn't seem to be effective, but I don't see this mentioned in neither the readme nor changelog, so wanted to make sure ;]

**Comment by timgraham** [comment]
Correct. This backend has `DatabaseFeatures.indexes_foreign_keys = False`, and here are the relevant changes to the Django tests: https://github.com/django/django/commit/ede9fac75807fe5810df66280a60e7068cc97e4a.
