### ISSUE TITLE
Add telemetry query at start-up time

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/django-cockroachdb#214]
We would like to start gathering telemetry on the usage of adapters like django-cockroachdb so that we have some notion of their popularity.

To support this, please add the following query at app start-up time:
```
SELECT crdb_internal.increment_feature_counter('Django %d.%d')
```
where the placeholders are the major and minor Django version numbers.

A couple additional details here:
- Ideally the query should be executed once at start-up time. In ActiveRecord we accomplished this by executing the query when the connection pool is initialized but there may be a better spot in Django.
- Depending on the CockroachDB version, the `increment_feature_counter` built-in may or may not be defined. (We added it in v21.1.) So we should ensure that an error is not bubbled up to the user if the query fails.
- We would like to execute this query by default, but please also add a setting which allows the user to disable it. (In ActiveRecord we called this `disable_cockroachdb_telemetry`.)

**Comment by timgraham** [comment]
Is it appropriate to skip the query when running Django's own test suite (for example, locally or on continuous integration)? We could use the setting for this, but to avoid having to update the settings files for existing builds, we can also easily check for an environment variable that Django's test suite sets.

**Comment by solongordon** [comment]
Yes that's appropriate, and an environment variable sounds fine to me if that simplifies things.

**Comment by timgraham** [comment]
Solon, would you like to review[ the patch](https://github.com/cockroachdb/django-cockroachdb/pull/216) (especially the wording in the documentation)? Thanks.

**Comment by vy-ton** [comment]
cc @rafiss to find reviewer for the patch

**Comment by vy-ton** [comment]
@timgraham when you have them, can you copy/paste the hashes that correspond to each Django version that's being tracked?

**Comment by timgraham** [comment]
Do you mean the commit hashes for this patch? This will only be added starting with Django 3.2 (the latest version as of now) as it's the minimum Django version that will support CockroachDB 21.1.x. (see [What versions of CockroachDB can I use with each version of Django?](https://github.com/cockroachdb/django-cockroachdb/wiki#what-versions-of-cockroachdb-can-i-use-with-each-version-of-django)).

**Comment by timgraham** [comment]
I'm not sure how to get those hashes.

**Comment by rafiss** [comment]
@vy-ton the hashes are sha256 checksums. they can be found with these commands:

```
❯ echo 'Django 3.0' | sha256sum
14adb292d2b5f51da817153fa061474f7b9345a55c583bcacfd01e5272e6220e  -
❯ echo 'Django 3.1' | sha256sum
ae10f0770e238b33a8c0ddb1bb6f3b54b3c488dde060ad1cab0aec90ac057fd0  -
❯ echo 'Django 3.2' | sha256sum
f2fce0d91eaf91914068e3f64578fca19b049ec29a5966992fb1977d469877c9  -
```
