### ISSUE TITLE
Is CockroachDB's search functionality compatible with Postgres'?

### ISSUE THREAD

**Issue by SebJansen** [cockroachdb/django-cockroachdb#226]
More specifically, I was wondering if CRDB can be searched through like Postgres can, as described in the Django docs: https://docs.djangoproject.com/en/3.2/ref/contrib/postgres/search/

**Comment by timgraham** [comment]
`contrib.postgres` isn't supported by this package. It might be possible to support it or parts of it in the future, but CockroachDB doesn't yet support full text search (https://github.com/cockroachdb/cockroach/issues/7821).
