### ISSUE TITLE
Incorrect results returned from startswith query

### ISSUE THREAD

**Issue by piotrb5e3** [cockroachdb/django-cockroachdb#243]
Hi,
We're seeing incorrect query results when filtering with `startswith` on a unique text field with a filter value that contains `_` (`%` and other special characters may also be affected). Most likely caused by cockroachdb/cockroach#44123.

The workaround would be to explicitly send `ESCAPE '\'` whenever a `LIKE` query is performed.

Reproduction example: [piotrb5e3/crdb-django-startswith-issue-repro](https://github.com/piotrb5e3/crdb-django-startswith-issue-repro)

Version information:
* cockroachdb: v21.1.12 and v21.2.2
* django-cockroachdb: 3.2.1 and 3.2.2
* django: 3.2.10

**Comment by timgraham** [comment]
Thanks for the report. I'm not sure that adding workarounds here for bugs in CockroachDB is the best use of resources.

**Comment by rafiss** [comment]
Thanks for bringing https://github.com/cockroachdb/cockroach/issues/44123 back to our attention. That's getting fixed in the database, and a fix should be getting backported to v21.1 and v21.2. Once it's available, can you try and let us know if you stop seeing the incorrect behavior?
