### ISSUE TITLE
Add support for StdDev and Variance aggregates

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/django-cockroachdb#25]
Django and PostgreSQL support both population and sample versions of standard deviation and variance. It looks like cockroachdb only supports one version (population or sample)? [The docs](https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#aggregate-functions) don't specify which.

No changes would be needed to Django if the functions are called `stddev_samp()`, `stddev_pop`,  `var_samp()`, and `var_pop()` [(matching PostgresSQL)](https://www.postgresql.org/docs/current/functions-aggregate.html).

**Comment by rohany** [comment]
https://github.com/cockroachdb/cockroach/issues/41274 is a related issue, for some of the other aggregates we don't support.

**Comment by timgraham** [comment]
https://github.com/cockroachdb/cockroach/commit/b5dd33fdbbf478a70bc60c27384be453edd3af91 added the `stddev_samp` alias. I created https://github.com/cockroachdb/cockroach/issues/48101 to add the `var_samp` alias and https://github.com/cockroachdb/cockroach/issues/48103 for `stddev_pop` and `var_pop`.

**Comment by timgraham** [comment]
All issues addressed as of CockroachDB 20.2.
