### ISSUE TITLE
add django as a dependency

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/django-cockroachdb#291]
Relaying feedback that I received from one of our customers:

> App devs have run into problems during upgrade of django-cockroachdb. The plugins dependencies do not seem to limit usage of the old version of django. For example you can recreate by:
> 1. Use Pipenv to set up django project
> 2. Freeze django to version 4.x.x
> 3. Run pipenv
> 4. See that the lockfile in django_cockroachdb is 5.0.0
> 5. App crashes

I believe the crash is happening due to the runtime version check in https://github.com/cockroachdb/django-cockroachdb/blob/ef465e1fa63a5045a450877b4bdd5e9931fa9e9a/django_cockroachdb/utils.py#L6

Can we check earlier for this mixed configuration? Perhaps with something like `install_requires=[“django>=4.0.0<5.0.0”]`?

**Comment by timgraham** [comment]
I would certainly freeze a major dependency like Django (at least something like `5.0.*` if you don't want to pin the micro version number) as well as the corresponding `django-cockroachdb==5.0.*`. In the large projects I've worked on, upgrading to the next major version of Django usually requires non-trivial testing and changes for backward-incompatible changes in Django. As you said, often third-party Django apps aren't immediately compatible with new versions of Django either, however, they may not necessarily specify a maximum version of Django in `install_requires`. I wouldn't rely on a pip/poetry/pipenv analysis to determine what version of Django is safe to use.

**Comment by timgraham** [comment]
This complaint was also made on another backend that I maintain. With modern package management tools, it appears that the benefit of adding Django to `install_requires` may outweigh the drawback I articulated, so I'm going to do it starting with `django-cockroachdb 5.1`.
