### ISSUE TITLE
Firing many deletes in a row won't make the objects drop properly

### ISSUE THREAD

**Issue by lindenb1** [cockroachdb/django-cockroachdb#294]
If I have the following in Django, which is a very simply API delete view:

```
@api_view(['DELETE'])
@authentication_classes([])
@permission_classes([IsAuthenticated])
def delete_my_model_entry(request, pk):
    try:
        # Fetch the object to be deleted
        my_model_entry = MyModel.objects.get(pk=pk)
        
        # Delete the object
        my_model_entry.delete()

        return Response(status=status.HTTP_204_NO_CONTENT)

    except ObjectDoesNotExist:
        return Response({'error': 'Object not found'}, status=status.HTTP_404_NOT_FOUND)
    except Exception as e:
        return Response({'error': str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
```

But when I fire against this function for like 6 times in 2 seconds, at least 2/6 objects were not deleted ... I also don't get an error or so, they just simply don't drop from the DB.

**Comment by timgraham** [comment]
I think you'll need to debug the issue further. It seems doubtful to me that Django is at fault, but if you find that it is, we can certainly reopen this issue. The only thing that comes to mind is [a transaction failure](https://www.cockroachlabs.com/blog/what-to-do-when-a-transaction-fails-in-cockroachdb/), however, I'd expect you would see an error in that case.

**Comment by lindenb1** [comment]
Well I totally understand your argumentation here, but I don't have any transactional failure here, I also don't have any, 40001 errors or so. My backend is responding with http 200, I really don't have any clue where this behavior might originate from, I'm running on psycopg2 (v. 2.9.9) build it from source, also not using the binary version or so...
Also at the CockroachDB I don't see any errors, The only thing that is working so far is setting a timeout of 0.5 seconds at my view, so that the user can't delete that fast, but this kinda sucks and is also not a good solution at all.

**Comment by rafiss** [comment]
One way to debug this further is to turn on statement execution logging. You can use the `sql.trace.log_statement_execute` cluster setting to do this (with `SET CLUSTER SETTING sql.trace.log_statement_execute = true`; more details are in [these docs](https://www.cockroachlabs.com/docs/stable/logging-overview)). This should only be enabled in development or test CRDB clusters, since it enables expensive logging. It will show the exact statements that CRDB is executing and whether they succeeded or not.
