### ISSUE TITLE
Async support?

### ISSUE THREAD

**Issue by alikud** [cockroachdb/django-cockroachdb#297]
Hey, can we use this package as async db driver for cocroach? Or better to use asyncpg ? 
We currently use this package, but want to UP django version to 4.2.x and migrate to async driver.

In tutorial  https://www.cockroachlabs.com/docs/stable/build-a-python-app-with-cockroachdb-django?filters=local 
i see that psycopg-2 is used, but django-cockroachdb==5.0 is 5.0, and i want to know, are some async support in 5.0? 
>>
psycopg2-binary
django==5.0.1
django-cockroachdb==5.0

**Comment by timgraham** [comment]
Support for Psycopg 3 was added in Django 4.2, and it's also been tested with django-cockroachdb since then. I think async support should work, but let me know if you run into any issues.
