### ISSUE TITLE
unsupported database functions: sha224 and sha384

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/django-cockroachdb#81]
Django 3.0 [adds support](https://github.com/django/django/commit/0b70985f42da7a8eb2e206e6780681b7849564ef) for various SHA* database functions. 

They work out of the box on CockroachDB except for SHA224 and SHA384.

Django tests: `db_functions.text.test_sha224` and `db_functions.text.test_sha384`

**Comment by rafiss** [comment]
Link to CockroachDB issue: https://github.com/cockroachdb/cockroach/issues/42450

**Comment by timgraham** [comment]
These functions are added in CockroachDB 21.1.
