### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/django-cockroachdb#87]
Many of the other third-party database adapters have django in the name before the vendor. For example:

https://github.com/maxirobaina/django-firebird
https://github.com/lionheart/django-pyodbc/
https://pypi.org/project/django-mssql/

Would it be okay to rename this repo from cockroach-django to django-cockroach?

**Comment by jordanlewis** [comment]
I think a rename is fine, also want @rafiss's opinion, but I think `django-cockroachdb` might be more on brand for us.

**Comment by rafiss** [comment]
+1 on `django-cockroachdb`

**Comment by timgraham** [comment]
Do you have GitHub permissions to do the rename there?

**Comment by rafiss** [comment]
Yep, this is done now.
