### ISSUE TITLE
Rename engine

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/django-cockroachdb#88]
Currently the Python package as structured as `'cockroach.django'`, however, there's unlikely to be any other sub-modules, so I wonder if we should drop `.django` and simply have `cockroach`. This affects the value the user puts in their `DATABASES` setting under `ENGINE`. Currently:
```
DATABASES = {
    'default': {
        'ENGINE': 'cockroach.django',
        ....
    },
}
```
Other third-party engine names: `sql_server.pyodbc`, `firebird`, `django_pyodbc`, `sqlserver_ado`

**Comment by timgraham** [comment]
I'm proposing to use `django_cockroach`.

**Comment by jordanlewis** [comment]
how about `django_cockroachdb`?

**Comment by jordanlewis** [comment]
Would we be breaking convention by adding `db`? Are there other `db`-suffixed databases that *don't* have db in their suffix? I don't think this hugely matters, but if you think it's not unconventional, we'd prefer using the full `cockroachdb` "wordmark" when possible.

**Comment by timgraham** [comment]
Sounds good to me.
