### ISSUE TITLE
DATE_TRUNC('week', <value>) truncates to midnight Sunday rather than Monday

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/django-cockroachdb#92]
`DATE_TRUNC('week', <value>)` truncates to midnight Sunday on cockroachdb but midnight Monday on PostgreSQL (and other databases)... probably a bug?

The Django feature commit shows some affected tests: https://github.com/django/django/commit/a455e732a0011dfbd15eddaa4fe60cb9439326e0

PostgreSQL:
```sql
> SELECT DATE_TRUNC('week', '2019-11-13'::timestamp);
"2019-11-11 00:00:00"
```
cockroach:
```sql
> SELECT DATE_TRUNC('week', '2019-11-13'::timestamptz);
         date_trunc          
+---------------------------+
  2019-11-10 00:00:00+00:00
```

**Comment by rafiss** [comment]
Created https://github.com/cockroachdb/cockroach/issues/42612 to track this in the cockroachdb repo

**Comment by rafiss** [comment]
This should be fixed in the latest bleeding edge build.

**Comment by timgraham** [comment]
Confirmed.
